# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"TypedArray": "00_core.ipynb",
         "ArrayMeta": "00_core.ipynb",
         "Array": "00_core.ipynb",
         "conarray": "00_core.ipynb",
         "PandasDataFrame": "00_core.ipynb",
         "extract_ddf_from_model_fields": "00_core.ipynb",
         "DataFrameModelMetaclass": "00_core.ipynb",
         "BaseFrame": "00_core.ipynb",
         "delegates": "98_utils.ipynb"}

modules = ["core.py",
           "utils.py",
           "default_standard_lib.py"]

doc_url = "https://humble chuck.github.io/pydantic_pandas/"

git_url = "https://github.com/humble chuck/pydantic_pandas/tree/main/"

def custom_doc_links(name): return None
