# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DataFrame": "00_core.ipynb",
         "BaseModel": "00_core.ipynb",
         "TypedArray": "00_core.ipynb",
         "ArrayMeta": "00_core.ipynb",
         "ConstrainedArray": "00_core.ipynb",
         "BaseFrame": "00_core.ipynb",
         "RowModel": "01_row_model.ipynb",
         "parse_dataframe_records": "01_row_model.ipynb",
         "TypedRecordFrame": "01_row_model.ipynb",
         "RecordFrameMeta": "01_row_model.ipynb",
         "RecordFrame": "01_row_model.ipynb",
         "recordframe": "01_row_model.ipynb",
         "record_model": "01_row_model.ipynb",
         "delegates": "98_utils.ipynb",
         "dummy_df": "98_utils.ipynb"}

modules = ["core.py",
           "row_model.py",
           "utils.py",
           "default_standard_lib.py"]

doc_url = "https://schlinkertc.github.io/pydantic-pandas/"

git_url = "https://github.com/schlinkertc/pydantic_pandas/tree/master/"

def custom_doc_links(name): return None
