# AUTOGENERATED! DO NOT EDIT! File to edit: 99_default_standard_lib.ipynb (unless otherwise specified).

__all__ = ['pd', 'np', 'dt', 'List', 'Dict', 'Tuple', 'Optional', 'Union', 'Any', 'Type', 'ForwardRef', 'json']

# Cell

import pandas as pd
import numpy as np
import datetime as dt
import re
import json

from typing import (
    List,Dict,Tuple,
    Optional,Union,
    Any,Type,ForwardRef
)

#nbdev_comment _all_ = ['pd','np','dt','List', 'Dict', 'Tuple', 'Optional', 'Union', 'Any', 'Type', 'ForwardRef','json']